comments/urls.py
from django.conf.urls import patterns, url
from .views import (
    CommentCreateView, CommentDeleteView,
    LikeComment, UnlikeComment, CommentUpdateView)

urlpatterns = patterns(
    '',
    url(r'^create/$', CommentCreateView.as_view(), name='comment-create'),
    url(
        r'update/(?P<pk>[0-9]+)/$',
        CommentUpdateView.as_view(),
        name='comment-update'),
    url(r'^delete/(?P<pk>[-\w]+)$',
        CommentDeleteView.as_view(), name='comment-delete'),
    url(r'^like/$', LikeComment.as_view(), name='comment-like'),
    url(r'^unlike/$', UnlikeComment.as_view(), name='comment-unlike'),
)

main/urls.py
from django.conf.urls import patterns, url
from django.conf import settings
from django.conf.urls.static import static
from .lookups import FriendAutocomplete, CommunityAutocomplete
import views
from django.views.generic import TemplateView

urlpatterns = patterns(
    '',
    url(r'^$', views.LandingePageView.as_view(), name='index'),
    url(r'^trip/list/offered/trips', TemplateView.as_view(template_name="main/offered_trip_list.html")),
    url(r'^profiles/home', views.home, name='home'),
    url(
        r'^trip/filter/$', views.TripFilterView.as_view(),
        name='trip-filter'),
    url(
        r'^trip/new/$', views.TripCreateView.as_view(),
        name='trip-new'),
    url(r'^trip/list/(?P<pk>[-_\w]+)/$', views.TripDetailView.as_view(),
        name='trip-detail'),
    url(r'^trip/request/list/(?P<pk>[-_\w]+)/$',
        views.TripRequestList.as_view(),
        name='trip-request-list'),
    url(r'^trip/list/(?P<pk>[-_\w]+)/update/$', views.TripUpdateView.as_view(),
        name='trip-update'),
    url(r'^trip/list/(?P<pk>[-_\w]+)/delete/$', views.TripDeleteView.as_view(),
        name='trip-delete'),
    url(r'^trip/list/$', views.TripListView.as_view(), name='trip-list'),
    url(r'^user/list/$', views.UserListView.as_view(), name='user-list'),
    url(r'^requests/$', views.RequestListView.as_view(),
        name='request-list'),
    url(r'^friend/list$', views.FriendListView.as_view(),
        name='friend-list'),
    # url(r'^facebook/user/list/$', views.FacebookUserListView.as_view(),
    #     name='facebook-user-list'),
    url(r'data/$', 'data.test_data', name='populate'),
    # url(r'^group/create/$', views.GroupCreateView.as_view(),
    #     name='group-new'),
    url(r'^group/list/$', views.GroupListView.as_view(), name='group-list'),
    url(r'^group/list/(?P<pk>[-_\w]+)/$', views.GroupDetailView.as_view(),
        name='group-detail'),
    url(r'^group/list/(?P<pk>[-_\w]+)/update/$',
        views.GroupUpdateView.as_view(),
        name='group-update'),
    url(
        r'^friend-autocomplete/$',
        FriendAutocomplete.as_view(),
        name='friend-autocomplete',
    ),
    url(
        r'^community-autocomplete/$',
        CommunityAutocomplete.as_view(),
        name='community-autocomplete',
    ),
    url(r'^profile/(?P<pk>[-_\w]+)/$', views.ProfileDetailView.as_view(),
        name='profile'),
    url(r'^profile/(?P<pk>[-_\w]+)/update/$',
        views.ProfileUpdateView.as_view(),
        name='profile-update'),
    url(r'^location/(?P<pk>[-_\w]+)/update/$',
        views.LocationUpdateView.as_view(),
        name='location-update'),
    url(r'^feedback/submit/$',
        views.FeedbackView.as_view(),
        name='feedback-submit'),
    url(r'^connections/$',
        views.ConnectionsView.as_view(),
        name='connections'),


) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += patterns('',
                            url(r'^media/(?P<path>.*)$',
                                'django.views.static.serve', {
                                    'document_root': settings.MEDIA_ROOT,
                                }),
                            url(r'^static/(?P<path>.*)$',
                                'django.views.static.serve', {
                                    'document_root': settings.STATIC_ROOT,
                                }),
                            )

myproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from ajax_select import urls as ajax_select_urls

urlpatterns = [
    url(r'^auth/', include('authentication.urls', namespace="auth")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('main.urls')),
    url(r'^messages/',
        include('postman.urls', namespace='postman', app_name='postman')),
    url(r'^intern/messages/lookups/',
        include(ajax_select_urls)),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^comments/', include('comments.urls')),
]

comments/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator
from django.contrib.contenttypes.fields import (
    GenericForeignKey)
from django.contrib.contenttypes.models import ContentType


class Comment(models.Model):
    """ Represents an instance of Comment """

    content_type = models.ForeignKey(ContentType, null=True)
    object_id = models.PositiveIntegerField(null=True)
    content_object = GenericForeignKey('content_type', 'object_id')
    user = models.ForeignKey(User, null=True, blank=True)

    comment = models.CharField(max_length=512)
    likes_count = models.IntegerField(
        default=0,
        validators=[MinValueValidator(0)])
    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name='Created at')


class Like(models.Model):
    """
    Represents an instance of a Like
    belonging to a Comment
    """
    user = models.ForeignKey(User)
    comment = models.ForeignKey(Comment)

comments/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):

    """Author: Aly Yakan"""
    comment = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = Comment
        exclude = ('likes_count', 'dislikes_count', 'content_type', 'object_id',
                   'content_object')

comments/views.py
from django.views.generic import (
    CreateView, DeleteView, FormView,
    UpdateView)
from django.core.urlresolvers import reverse_lazy, reverse
from django.template.loader import render_to_string
from django.http import JsonResponse, HttpResponseRedirect, HttpResponse
from django.middleware.csrf import get_token
from comments.models import Comment, Like
from comments.forms import CommentForm
from django.contrib.contenttypes.models import ContentType
from django.conf import settings
from main import models
import re


class AjaxableResponseMixin(object):

    """
    Mixin to add AJAX support to a form.
    Must be used with an object-based FormView (e.g. CreateView)
    """

    def form_invalid(self, form):
        response = super(AjaxableResponseMixin, self).form_invalid(form)
        if self.request.is_ajax():
            return JsonResponse({
                'success': 0,
                'error': form.errors})
        else:
            return response

    def form_valid(self, form):
        # We make sure to call the parent's form_valid() method because
        # it might do some processing (in the case of CreateView, it will
        # call form.save() for example).
        response = super(AjaxableResponseMixin, self).form_valid(form)
        if self.request.is_ajax():
            csrf_token_value = get_token(self.request)
            html = render_to_string(
                "comments/comment.html",
                {'object': self.object,
                 'user': self.request.user,
                 'form': CommentForm(),
                 'liked': False,
                 'csrf_token': csrf_token_value,
                 'allow_likes': getattr(
                    settings,
                    'COMMENTS_ALLOW_LIKES',
                    True)
                 })
            try:
                data = {
                    'success': 1,
                    'html': html,
                    'id': self.object.id
                }
            except:
                data = {
                    'success': 1,
                }
            return JsonResponse(data)
        else:
            return response


class CommentCreateView(AjaxableResponseMixin, CreateView):

    """
    Class that creates an instance of model:comment.Comment

    """
    form_class = CommentForm
    model = Comment
    template_name = 'comments/comment_form.html'
    success_url = reverse_lazy('comment-create')

    def form_valid(self, form):
        comment = form.save(commit=False)
        try:
            content_type = ContentType.objects.get(
                app_label=self.request.POST['app_name'],
                model=self.request.POST['model'].lower())
            model_object = content_type.get_object_for_this_type(
                id=self.request.POST['model_id'])
            comment.content_object = model_object
        except:
            pass
        comment.comment = self.convert_mentions(comment.comment)
        comment.save()
        return super(CommentCreateView, self).form_valid(form)

    def convert_mentions(self, message):
        pat = re.compile(r"@(\w+)")
        try:
            # get all tagged trips
            tagged_trip_list = pat.findall(message)
            # get first tagged trip
            first_trip = tagged_trip_list[0]
            # confvert tagged trip to hyper link if it does exist
            first_trip = models.Trip.objects.get(name=first_trip)
            # first_trip_name = first_trip.name
            first_trip_id = first_trip.id
            this_trip_handle = reverse('trip-detail', args=[first_trip_id])
            # sub @trip_name to trip_name
            new_message = re.sub(r'(@\w+)', r"<a href='#'>" + first_trip.name + "</a>", message)
            # embed trip-detail url
            new_message = new_message.replace('#', this_trip_handle)
            return new_message
        except:
            return message


class CommentDeleteView(DeleteView):

    """
    Class that deletes an instance of model:comment.Comment

    """
    model = Comment
    success_url = reverse_lazy('comment-create')

    def get(self, request, *args, **kwargs):
        """
        Calls the delete() method on the fetched object and then
        redirects to the success URL.
        """
        try:
            id = request.GET['id']
            self.object = Comment.objects.get(id=id)
            if (self.object.user.id == request.user.id):
                self.object.delete()
                data = {"success": "1",
                        "count": Comment.objects.count()}
            else:
                data = {"success": "0"}
        except:
            data = {"success": "0"}
        if request.is_ajax():
            return JsonResponse(data)
        else:
            return HttpResponseRedirect(self.success_url)


class LikeComment(FormView):

    """
    Class that creates an instance of model:comment.Like
    """

    def get(self, request, *args, **kwargs):
        comment_id = request.GET['comment_id']
        likes_count = 0
        data = {}

        # Check if user is authenticated.
        if not request.user.is_authenticated():
            # Return if user is not authenticated.
            data['success'] = 0
            data['error'] = "You have to sign in first"
            return JsonResponse(data)

        user = request.user
        try:
            # Check if the comment with the requested id exists.
            comment = Comment.objects.get(id=comment_id)
            likes_count = comment.likes_count
            try:
                # Check if the user already liked the comment,
                # Do nothing in this case.
                Like.objects.get(comment=comment, user=user)
                data['success'] = 0
                data['error'] = "You have already liked this comment"
            except:
                # Create a like on the comment in case the user hasn't
                # liked it already.
                Like.objects.create(comment=comment, user=user).save()
                likes_count += 1
                comment.likes_count = likes_count
                comment.save()
                data['likes_count'] = likes_count
                data['success'] = 1
        except:
            # Return an error where the comment might have been removed.
            data['success'] = 0
            data['error'] = "This comment might have been removed"
        return JsonResponse(data)


class UnlikeComment(FormView):

    """
    Class that deletes an instance of model:comment.Like
    """

    def get(self, request, *args, **kwargs):
        comment_id = request.GET['comment_id']
        likes_count = 0
        data = {}

        # Check if user is authenticated.
        if not request.user.is_authenticated():
            # Return if user is not authenticated.
            data['success'] = 0
            data['error'] = "You have to sign in first"
            return JsonResponse(data)

        user = request.user
        try:
            # Check if the comment with the requested id exists.
            comment = Comment.objects.get(id=comment_id)
            likes_count = comment.likes_count
            try:
                # Check if the user already liked the comment,
                # Unlike the comment in this case.
                Like.objects.get(comment=comment, user=user).delete()
                likes_count -= 1
                comment.likes_count = likes_count
                comment.save()
                data['success'] = 1
                data['likes_count'] = likes_count
            except:
                # If the user hasn't liked it, return an error.
                data['success'] = 0
                data['error'] = "You have to like the comment first"
        except:
            # Return an error where the comment might have been removed.
            data['error'] = "This comment might have been removed"
        return JsonResponse(data)


class CommentUpdateView(AjaxableResponseMixin, UpdateView):

    """
    Class that updates an instance of model:comment.Comment
    """
    form_class = CommentForm
    model = Comment
    template_name = 'comments/comment_edit_form.html'
    success_url = reverse_lazy('comment-create')

    def form_valid(self, form):
        if not self.object.user:
            return HttpResponse('not allowed')
        else:
            if (self.request.user.is_authenticated and
                    self.object.user == self.request.user):
                form.save()
                return super(CommentUpdateView, self).form_valid(form)
            else:
                return HttpResponse('not authenticated')

    def is_valid(self, form):
        print "helllooo"

comments/templates/comments/base_comment.html
{% extends "main/base.html" %}
{% load static %}

{% load static comments_tags %}
{% include_jQuery %}
{% get_comments object request.user %}
{% comment_form object user %}

comments/templates/comments/comment.html
<li class="media">
    <div class="post-comment">
        <a class="pull-left">
<!--             <img class="media-object" src="{/static/images/blogdetails/2.png}" alt="">
 -->            <img class="media-object" width ="145" height="120" src="{{ object.user.get_profile.avatar.url}}" alt="">

        </a>
        <div class="media-body">
            <span><i class="fa fa-user"></i>Posted by <a href="#">
            {% if object.user %}
                <p> {{ object.user.username }} </p>
            {% else %}
                <p>Guest </p>
            {% endif %}</a></span>
            <p id='comment-{{ object.id }}'> {{ object.comment|safe }} </p>
            <ul class="nav navbar-nav post-nav">
                <li><a href="#"><i class="fa fa-clock-o"></i>{{ object.created_at }}</a></li>
            </ul>
        </div>
    </div>
</li>



<!--  <p id='comment-{{ object.id }}'> {{ object.comment }} </p>
 <div id="comment-edit-{{ object.id }}" hidden>
	{% include "comments/comment_edit_form.html" with pk=object.id form=form %}
</div>
 <p>{{ object.created_at }}</p>

 <p id="likes-count-{{ object.id }}" >Likes: {{ object.likes_count }}</p>

{% if object.user %}
	<p>By: {{ object.user.username }} </p>
{% else %}
	<p>By: Guest </p>
{% endif %}

{% if object.user %}
	{% if object.user.id == user.id %}
		<form class="comment-delete-form" method='DELETE' action="{% url "comment-delete" object.pk %}">
			<input value="{% csrf_token %}" id="csrf" hidden>
			{% csrf_token %}
			<input type="submit" value="Delete" class="comment-delete-btn" data-id="{{ object.id }}"/>
		</form>
	{% endif %}
{% endif %}

{% if object.user %}
	{% if object.user.id == user.id %}
		<button class='comment-edit-class' data-id='{{ object.id }}'> Edit</button>	
	{% endif %}
	<br>
{% endif %}

{% if allow_likes %}	
	{% if liked %}

		<button class="like-comment-btn" id="like-btn-{{ object.id }}" data-like="liked" data-id="{{ object.id }}">Unlike</button>	

	{% else %}

		<button class="like-comment-btn" id="like-btn-{{ object.id }}" data-like="like" data-id="{{ object.id }}">Like</button>
		
	{% endif %}	
{% endif %} -->

comments/templates/comments/comment_edit_form.html
	<form action="{% url 'comment-update' object.id %}" method="post" class="edit-form" id="edit-form" data-id='{{ object.id }}'>
	{% csrf_token %}
		<P id="edit-form-errors"></P>
		 Edit : <input id='input-comment-{{ object.id }}' name='comment' value="{{ object.comment }}">
		 <input id="id_user" name="user" value="{% if user.is_authenticated %}{{ user.id }}{% endif %}" hidden>
		 <input type="submit" value="Submit" />
	</form>

comments/templates/comments/comment_form.html
{% load comments_tags %}

{% if not user.is_authenticated and not allow_anonymous %}
{% else %}
	<div id="comment-input-div">
		<form method="POST" action="{% url "comment-create" %}" class="add-comment-form">
			{% csrf_token %}
			{{ form.errors }}
			{{ form.comment.label }}
			<br>
			<div class="form-group">
				<textarea cols="40" id="id_comment" name="comment" rows="5" class="form-control"></textarea>
			</div>
			{% if target %}	
				<input name="model" value="{% get_model_name target %}" hidden>
				<input name="model_id" value="{{ target.id }}" hidden>
				<input name="app_name" value="{% get_app_name target %}" hidden>
			{% endif %}
			<input id="id_user" name="user" value="{% if user.is_authenticated %}{{ user.id }}{% endif %}" hidden> <br>
			<input type="submit" value="Post" id="add-comment" class="btn btn-primary btn-block" />
		</form>
	</div>
{% endif %}

comments/templates/comments/comments.html
{% load static comments_tags %}

		<script src="{% static "js/jquery.js" %}"></script>
		<script src="{% static "js/comments.js" %}"></script>
	
	<div class="comments-wrapper">
		<h3> Comments </h3>
		<div class="comments"  style="height:450px;width:100%;overflow-y:scroll">
			{% for comment, liked in comment_liked %}

				<div id="comment-div-{{ comment.id }}" >
					{% include "comments/comment.html" with object=comment liked=liked form=form %}
				</div>

			{% empty %}

				<h3 id='no-comments'> No Comments </h3>

			{% endfor %}
		</div>
	</div>

comments/templates/comments/jQuery.html
<script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
<script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>