authentication/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from .views import UserRegistrationView
# from django.views.generic import TemplateView
# from .views import UserChangePassword, LoginView


urlpatterns = [
    url(r'^user/new/$', UserRegistrationView.as_view(), name='user-new'),
    # url(r'^user/logout/$', auth_views.logout,
    #     {'next_page': '/auth/user/login/'}, name='user-logout'),
    url(r'^user/logout/$', auth_views.logout,
        {'next_page': '/'}, name='user-logout'),
    url(r'^user/login/$', auth_views.login,
        {'template_name': 'registration/login.html'},
        name='user-login'),
    # url(
    #     r'^user/reset/$', auth_views.password_reset,
    #     {'template_name': 'registration/password_reset.html'},
    #     name='user-reset'),
    # url(
    #     r'^resetpassword/passwordsent/$',
    #     auth_views.password_reset_done,
    #     {'template_name': 'registration/reset_done.html'},
    #     name='password_reset_done'),
    # url(
    #     r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    #     auth_views.password_reset_confirm,
    #     {'template_name': 'registration/confirm_reset.html'},
    #     name='password_reset_confirm'),
    # url(
    #     r'^reset/done/$', auth_views.login,
    #     name='password_reset_complete'),
    # url(r'^user/manage/$', TemplateView.as_view(
    #     template_name='registration/manage-account.html'), name='user-manage'),
    # url(r'^user/change-password/$', UserChangePassword.as_view(),
    #     name='user-change-password'),

]

main/urls.py
from django.conf.urls import patterns, url
from django.conf import settings
from django.conf.urls.static import static
from .lookups import FriendAutocomplete, CommunityAutocomplete
import views
from django.views.generic import TemplateView

urlpatterns = patterns(
    '',
    url(r'^$', views.LandingePageView.as_view(), name='index'),
    url(r'^trip/list/offered/trips', TemplateView.as_view(template_name="main/offered_trip_list.html")),
    url(r'^profiles/home', views.home, name='home'),
    url(
        r'^trip/filter/$', views.TripFilterView.as_view(),
        name='trip-filter'),
    url(
        r'^trip/new/$', views.TripCreateView.as_view(),
        name='trip-new'),
    url(r'^trip/list/(?P<pk>[-_\w]+)/$', views.TripDetailView.as_view(),
        name='trip-detail'),
    url(r'^trip/request/list/(?P<pk>[-_\w]+)/$',
        views.TripRequestList.as_view(),
        name='trip-request-list'),
    url(r'^trip/list/(?P<pk>[-_\w]+)/update/$', views.TripUpdateView.as_view(),
        name='trip-update'),
    url(r'^trip/list/(?P<pk>[-_\w]+)/delete/$', views.TripDeleteView.as_view(),
        name='trip-delete'),
    url(r'^trip/list/$', views.TripListView.as_view(), name='trip-list'),
    url(r'^user/list/$', views.UserListView.as_view(), name='user-list'),
    url(r'^requests/$', views.RequestListView.as_view(),
        name='request-list'),
    url(r'^friend/list$', views.FriendListView.as_view(),
        name='friend-list'),
    # url(r'^facebook/user/list/$', views.FacebookUserListView.as_view(),
    #     name='facebook-user-list'),
    url(r'data/$', 'data.test_data', name='populate'),
    # url(r'^group/create/$', views.GroupCreateView.as_view(),
    #     name='group-new'),
    url(r'^group/list/$', views.GroupListView.as_view(), name='group-list'),
    url(r'^group/list/(?P<pk>[-_\w]+)/$', views.GroupDetailView.as_view(),
        name='group-detail'),
    url(r'^group/list/(?P<pk>[-_\w]+)/update/$',
        views.GroupUpdateView.as_view(),
        name='group-update'),
    url(
        r'^friend-autocomplete/$',
        FriendAutocomplete.as_view(),
        name='friend-autocomplete',
    ),
    url(
        r'^community-autocomplete/$',
        CommunityAutocomplete.as_view(),
        name='community-autocomplete',
    ),
    url(r'^profile/(?P<pk>[-_\w]+)/$', views.ProfileDetailView.as_view(),
        name='profile'),
    url(r'^profile/(?P<pk>[-_\w]+)/update/$',
        views.ProfileUpdateView.as_view(),
        name='profile-update'),
    url(r'^location/(?P<pk>[-_\w]+)/update/$',
        views.LocationUpdateView.as_view(),
        name='location-update'),
    url(r'^feedback/submit/$',
        views.FeedbackView.as_view(),
        name='feedback-submit'),
    url(r'^connections/$',
        views.ConnectionsView.as_view(),
        name='connections'),


) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += patterns('',
                            url(r'^media/(?P<path>.*)$',
                                'django.views.static.serve', {
                                    'document_root': settings.MEDIA_ROOT,
                                }),
                            url(r'^static/(?P<path>.*)$',
                                'django.views.static.serve', {
                                    'document_root': settings.STATIC_ROOT,
                                }),
                            )

myproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from ajax_select import urls as ajax_select_urls

urlpatterns = [
    url(r'^auth/', include('authentication.urls', namespace="auth")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('main.urls')),
    url(r'^messages/',
        include('postman.urls', namespace='postman', app_name='postman')),
    url(r'^intern/messages/lookups/',
        include(ajax_select_urls)),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^comments/', include('comments.urls')),
]

main/models.py
from __future__ import unicode_literals
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from django.db import models
from comments.models import Comment
from django.contrib.contenttypes.fields import GenericRelation
from ckeditor.fields import RichTextField
from allauth.socialaccount.models import SocialAccount
# from helpers import dismiss_trip
# Create your models here.


class NameModel(models.Model):
    """
    Base model for name and slug.
    """
    name = models.CharField(max_length=256)
    slug = models.CharField(max_length=256)
    created_at = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(NameModel, self).save(*args, **kwargs)

    def __unicode__(self):
        if self.name:
            return self.name
        else:
            return str(super(NameModel))

    class Meta:
        abstract = True


class Community(NameModel):

    """ SoCar Closed Community."""
    created_by = models.ForeignKey(User, related_name="author")
    members = models.ManyToManyField(User, related_name="community_members")

    def __unicode__(self):
        return self.name


class Trip(NameModel):
    """
    Trips.

    """
    # class Meta:
    # unique_together = (('name', 'user'),)  # composite primary key.

    GUEST_CHOICES = (
        (1, '1 Guest'),
        (2, '2 Guests'),
        (3, '3 Guests'),
        (4, '4 Guests'),
    )
    driver = models.ForeignKey(User, related_name="driver")
    guests = models.IntegerField(choices=GUEST_CHOICES, default=1)
    date = models.DateField()
    time = models.TimeField()
    # google maps attributes
    source_latitude = models.CharField(max_length=256, null=False)
    source_longitude = models.CharField(max_length=256, null=False)
    destination_latitude = models.CharField(max_length=256, null=False)
    destination_longitude = models.CharField(max_length=256, null=False)
    source_area = models.CharField(max_length=128, default='')
    destination_area = models.CharField(max_length=128, default='')
    distance = models.CharField(max_length=256, null=True)
    restrict_to_women = models.BooleanField(default=0)

    # permissions
    communities = models.ManyToManyField(Community, blank=True)
    # restrict_to_women = models.BooleanField(default=False)

    def relevant_group(self):
        return Group.objects.get(trip_id=self.id)

    def retrieve_guest_list(self):
        # retrieve guests relative to trip
        guest_list = Guest.objects.filter(trip=self, accepted=True).values_list('guest', flat=True)
        user_list = []
        for entry in guest_list:
            user = User.objects.get(id=entry)
            user_list.append(user)
        return user_list

    def all_participants(self):
        return Guest.objects.filter(trip_id=self.id, accepted=True).values_list('guest', flat=True)

    def delete(self, *args, **kwargs):
        try:
            # send conclusion email
            # dismiss_trip(self)
            # remove associated guests
            Guest.objects.filter(trip_id=self.id).delete()
            #
            group = Group.objects.get(trip_id=self.id)
            # remove group members
            group.members.through.objects.filter(group=group).delete()
            # remove respective group
            group.delete()
            # remove trip
        except:
            pass
        super(Trip, self).delete(*args, **kwargs)


class Guest(models.Model):
    """
    Trip Guests.
    """
    guest = models.ForeignKey(User, related_name="guest")
    trip = models.ForeignKey(Trip)
    accepted = models.BooleanField(default=False)


class Friend(models.Model):
    """
    Friend Requests.
    """
    sender = models.ForeignKey(User, related_name="sender")
    receiver = models.ForeignKey(User, related_name="receiver")
    accepted = models.BooleanField(default=False)


class Group(NameModel):

    """ SoCar Trip Groups """
    trip = models.OneToOneField(Trip, related_name="trip")
    created_by = models.ForeignKey(User, related_name="created_by")
    members = models.ManyToManyField(User, related_name="members")
    # members = models.CharField(max_length=256)
    comments = GenericRelation(Comment)

    def __unicode__(self):
        return self.name


class Location(models.Model):
    area = models.CharField(max_length=256)
    longitude = models.CharField(max_length=256)
    latitude = models.CharField(max_length=256)
    # bounded radius.
    upper_bound = models.CharField(max_length=256)
    lower_bound = models.CharField(max_length=256)


class Profile(models.Model):
    """

    User's Profile

    To do: CHOICES are to be modified.
    """
    GENDER_CHOICES = (
        ('Male', 'Male'),
        ('Female', 'Female'),
    )

    CAR_NO_CAR_CHOICES = (
        ('No Car', 'No Car'),
        ('Has Car', 'Has Car'),
    )
    user = models.OneToOneField(User)
    avatar = models.ImageField(upload_to='profile/', null=True, blank=True)
    bio = RichTextField(null=True, blank=True)
    phone_number = models.CharField(max_length=256, null=True, blank=True)
    slug = models.CharField(max_length=256)
    car = models.CharField(
        max_length=256, choices=CAR_NO_CAR_CHOICES, default="Has Car")
    gender = models.CharField(
        max_length=256, choices=GENDER_CHOICES, default="Male")
    location = models.ForeignKey(Location, null=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.user.username)
        super(Profile, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.user.username


class Feedback(models.Model):
    """
    Model stores visitor's/user's feedback.
    """
    feedback = models.CharField(max_length=512)
    session = models.CharField(max_length=256)
    user = models.ForeignKey(User, null=True)


class UrlHitCounter(models.Model):
    """
    Counts the number of visits for the following urls eg. index page.
    """
    session_key = models.CharField(max_length=256, null=True)
    index = models.IntegerField(default=1)


class ObjectHitCounter(models.Model):
    """
    Counts the number of hits for the following models eg.main.Trip, trips_created.
    """
    sign_up_forms = models.IntegerField(default=0)
    trips_created = models.IntegerField(default=0)
    groups_created = models.IntegerField(default=0)


def get_social_account(self):
    # Fetch user's relative social account
    return SocialAccount.objects.get(user_id=self.id, provider='facebook')


def get_profile(self):
    # Fetch user's relative profle
    return Profile.objects.get(user_id=self.id)


def get_gender(self):
    gender = Profile.objects.get(user_id=self.id).gender
    if gender == "Male":
        return 0
    else:
        return 1

# Add function to auth/User model
User.add_to_class('get_social_account', get_social_account)
User.add_to_class('get_profile', get_profile)
User.add_to_class('get_gender', get_gender)

main/templates/main/base.html
<!DOCTYPE html>
{% load socialaccount %}
{% providers_media_js %}
{% load staticfiles %}
{% load static %}


<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title> {% block title %} {% endblock title %}| SoCar</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/font-awesome.min.css" rel="stylesheet">
    <link href="/static/css/lightbox.css" rel="stylesheet"> 
    <link href="/static/css/animate.min.css" rel="stylesheet"> 
    <link href="/static/css/main.css" rel="stylesheet">
    <link href="/static/css/responsive.css" rel="stylesheet">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css" />

    <!--[if lt IE 9]>
        <script src="js/html5shiv.js"></script>
        <script src="js/respond.min.js"></script>
    <![endif]-->       
    <link rel="shortcut icon" href="images/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/static/images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/static/images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/static/images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="/static/images/ico/apple-touch-icon-57-precomposed.png">
   <!--  <link rel="stylesheet" type="text/css" href="/static/css/token-input.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/token-input-facebook.css" /> -->
    {% block link %} {% endblock link %}
    {% block extrahead %} {% endblock %}
</head><!--/head-->
<body>
    <header id="header">       
        <div class="navbar navbar-inverse" role="banner">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="index.html">
<!--                         <h1><img src="/static/images/logo.png" alt="logo"></h1>
 -->                    </a>   
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                         <li><a>{{user.username}}</a></li>
                        <li><a href='{% url "profile" user.id%}'>Profile</a></li>                                        
                        <li class="dropdown"><a href="/">SoCar <i class="fa fa-angle-down"></i></a>
                            <ul role="menu" class="sub-menu">
                                <li><a href='{% url "trip-list"%}'>SoCar Trips</a></li>
                                <li><a href='{% url "trip-new"%}'>Offer A Trip</a></li>
                                <li><a href='{% url "connections"%}'>Connections</a></li>
                               <!--  <li><a href='{% url "friend-list"%}'>Friends</a></li>
                                <li><a href='{% url "user-list"%}'>People Near You</a></li> -->
                                <li><a href='{% url "group-list"%}'>Groups And Communities</a></li>
                                <li><a href='/messages'>Messages</a></li>
                            </ul>
                        </li>
                        <li><a href='{% url "auth:user-logout"%}'>Logout</a></li>   
                        {% else %}
                            <li><a href='{% url "auth:user-login"%}'>Login</a></li>
                            <li><a href='{% url "auth:user-new"%}'>Sign up</a></li>
<!--                             <li><a href="{% provider_login_url "facebook" method="js_sdk" %}">Facebook Connect</a></li>
 -->                        {% endif %}              
                    </ul>
                </div>
            </div>
        </div>
    </header>
    <!--/#header-->

     <section id="page-breadcrumb">
        <div class="vertical-center sun">
             <div class="container">
                <div class="row">
                    <div class="action">
                        <div class="col-sm-12 ">
                            <h1 class="title">  {% block action %} {% endblock action%}</h1>
                            <h2>{% block extra_action %}{% endblock extra_action%}</h2>                            
                        </div>
                         <div class="col-sm-12 ">
                            <h1 class="title">  {% block action_2 %} {% endblock action_2%}</h1>                                                     
                        </div>
                    </div>
                </div>
            </div>
        </div>
   </section>
                            

    <!--/#action-->

    {% block content %}{% endblock content%}
    {% block postman_menu %} {% endblock postman_menu %}


    <footer id="footer">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 text-center bottom-separator">
                    <img src="/static/images/home/under.png" class="img-responsive inline" alt="">
                </div>
                <div class="col-md-4 col-sm-6">
                    <div class="testimonial bottom">
<!--                         <h2>Testimonial</h2>
 -->                        <div class="media">
                            <div class="pull-left">
<!--                                 <a href="#"><img src="/static/images/home/profile1.png" alt=""></a>
 -->                            </div>
                             <div class="col-md-4 col-sm-4">
                             </div>
                            <div class="media-body">
                                <blockquote>The man who goes alone can start today; but he who travels with another must wait till that other is ready.</blockquote>
                                <h3><a >- Henry David Thoreau</a></h3>
                            </div>
                         </div>
                        <div class="col-md-4 col-sm-4">
                        </div>
                        <div class="media">
                            <div class="pull-left">
<!--                                 <a href="#"><img src="/static/images/home/profile2.png" alt=""></a>
 -->                            </div>
                            <div class="media-body">
                                <blockquote>People don’t take trips, trips take people.</blockquote>
                                <h3><a>- John Steinbeck</a></h3>
                            </div>
                        </div>   
                    </div> 
                </div>
                <div class="col-md-3 col-sm-6">
                    <div class="contact-info bottom">
                        <h2>Contacts</h2>
                        <address>
                        E-mail: <a href="mailto:kareem.tarek04@gmail.com">kareem.tarek04@gmail.com</a> <br> 
                        Phone: +20 (012) 88777771  <br> 
                        </address>
                        {% block extra_footer %} {% endblock extra_footer %}

<!-- 
                        <h2>Address</h2>
                        <address>
                        Unit C2, St.Vincent's Trading Est., <br> 
                        Feeder Road, <br> 
                        Bristol, BS2 0UY <br> 
                        United Kingdom <br> 
                        </address> -->
                    </div>
                </div>
                <div class="col-md-4 col-sm-12">
                    <div class="contact-form bottom">
                        <h2>Feedback</h2>           
                        <form action="/feedback/submit/" method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <textarea class="form-control" cols="40" id="id_feedback" name="feedback" rows="10" placeholder="We'd really appreciate your feedback .. "></textarea>
                            </div>
                            <input type="submit" class="btn btn-submit" value="Send Feedback">
                        </form>
                    </div>  
                </div>
                <div class="col-sm-12">
                    <<!-- div class="copyright-text text-center">
                        <p>&copy; Your Company 2014. All Rights Reserved.</p>
                            <p>Designed by <a target="_blank" href="http://www.themeum.com">Themeum</a></p>
                    </div> -->
                </div>
            </div>
        </div>
    </footer>

    <!--/#footer-->
<!--/#footer-->
    <script type="text/javascript" src="/static/js/jquery.js"></script>

    <script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
    <script src="http://code.jquery.com/ui/1.11.1/jquery-ui.min.js"></script>
    <script type="text/javascript" src="/static/js/bootstrap.min.js"></script>
    
    <script type="text/javascript" src="/static/js/lightbox.min.js"></script>
    <script type="text/javascript" src="/static/js/wow.min.js"></script>
    <script type="text/javascript" src="/static/js/main.js"></script>
    {% block script %} {% endblock script %}
</body>

<style type="text/css">

#footer {
    margin-top: 20px;
}

</style>

main/templates/main/facebook_user_list.html
<div class="row well">
    <ul class="list-group " style="height:400px;overflow-y:scroll">
        {% for user in friend_add %}
            <li class="list-group-item">
                <div class="row">
                    <div class="col-sm-2" >
                        <img class="media-object" src="{{ user.get_social_account.get_avatar_url }}" alt="">
                    </div>
                    <div class="col-sm-6">
                        <h5>{{user.get_social_account.extra_data.name }}</h5>
                        <h5> Joined {{user.date_joined}}</h5>
                        <h5>
                        <span><a href="{{user.get_social_account.extra_data.link}}">Aly's Facebook </a></span> <br> <br>
                        </h5>
                        <span> 
                            <form action="" method="POST" class="friend-request-form{{user.id}}">
            					{% csrf_token %}
            					<select id="id_receiver" name="receiver" hidden>
            						<option value="{{user.id}}" selected="selected" ></option>
            					</select>
            					<select id="id_sender" name="sender" hidden>
            						<option value="{{current_user.id}}" selected="selected" ></option>
            					</select>
            					<input  id="friend-request-button{{user.id}}" type="button" name="friend-request-button" object="{{user.id}}"  value="Send Friend Request" class="btn btn-sm btn-primary" /> <br><br>
            				</form>
                        </span><br>
                    </div>
                </div>  
            </li>
            <br><br>
        {% endfor %}
</div>
         

main/templates/main/friend_request_list.html
<div class="row well">
    <ul class="list-group " style="height:400px;overflow-y:scroll">
        {% for request in friend_requests  %}
        <li class="list-group-item">
            <div class="row">
                <div class="col-sm-2">
                    <img class="media-object" src="/static/images/home/images/user-2.png" alt="">
                </div>
                <div class="col-sm-6">
                    <h3>{{request.sender.username}}</h3>
                    <h3>{{request.sender.email}}</h3>
                    <h3> Joined {{request.sender.date_joined}}</h3>
                    <span><a href="/profile/{{request.sender.id}}/">Check {{request.sender.username}}'s Profile </a></span>
                    <span> 
                        <form action="" method="POST" class="friend-form{{request.sender.id}}">
                            {% csrf_token %}
                            <select id="id_sender" name="sender" hidden>
                                <option value="{{request.sender.id}}" selected="selected" ></option>
                            </select>
                            <select id="id_receiver" name="receiver" hidden>
                                <option value="{{current_user.id}}" selected="selected" ></option>
                            </select>
                            <input  id="accept-friend-button{{request.sender.id}}" type="button" class="btn btn-sm btn-primary" object="{{request.sender.id}}" name="friend-button" value="Accept" /> 
                            <input id="reject-friend-button{{request.sender.id}}" type="button"  class="btn btn-sm btn-danger" object="{{request.sender.id}}"  name="friend-button" value="Reject" /> 
                        </form>
                    </span><br>
                </div>
            </div>  
            <br><br>
        </li>
        {% endfor %}
    </ul>
</div>                                    

main/templates/main/group_create_form.html
<h2> Create A Closed Community </h2> <br>
<div class="contact-form bottom">
	<p id="group-create-errors"></p>
    <form action="" method="post" id="group-create" >
        {% csrf_token %}
        <div class="form-group">	
            {{ form.as_p }}
        </div>
        <input type="submit"  class="btn btn-submit" value="Create Group" />
    </form>
</div>

main/templates/main/member_group_list.html
<div class="portfolio-items">
    {% for group in my_groups  %}
        <div class="col-xs-6 col-sm-7 col-md-4 portfolio-item ">
            <div class="portfolio-wrapper">
                <div class="portfolio-single">
                    <div class="portfolio-thumb">
                        <img src="/static/images/home/images/group-3.jpg" class="img-responsive" alt="">
                    </div>
                    <!-- <div class="portfolio-view">
                        <ul class="nav nav-pills">
                        <h3 class="post-title "> Members</h3>
                            {% for member in group.members.all %}
                               <li><span><a href="/profile/{{ member.id }}/"> &nbsp {{ member.username }} &nbsp   </a></span> </li>
                         {% endfor %}
                        </ul>
                    </div> -->
                </div>
                <div class="portfolio-info ">
                    <h2 class="post-title"><a href='{% url "group-detail" group.id%}'> {{group.name}} </a></h2> <br>
                </div>
            </div>
        </div>
    {% endfor%}
</div>

    <!--/#projects-->

main/templates/main/trip_requests.html
{% for request in requests  %}
    <div class="row">
        <div class="col-sm-2">
            <img class="media-object" src="/static/images/home/images/user-2.png" alt="">
        </div>
        <div class="col-sm-10">
            <h3>{{request.guest.username}}</h3>
            <h3>{{request.guest.email}}</h3>
            <span><a href="/profile/{{request.guest.id}}/">Check Profile </a></span>
            <span> 
                <form action="" method="POST"  class="participant-form{{request.guest.id}}" >
                    {% csrf_token %}
                    <select id="id_guest" name="guest" hidden>
                        <option value="{{request.guest.id}}" selected="selected" ></option>
                    </select>
                    <select id="id_trip" name="trip" hidden>
                        <option value="{{request.trip.id}}" selected="selected" ></option>
                    </select>
                    <input  id="accept-request-button{{request.guest.id}}"  name="participant-button"  type="button" value="Accept"  class="btn btn-sm btn-primary"  object="{{request.guest.id}}" trip="{{request.trip.id}}"/>
                    <input  id="reject-request-button{{request.guest.id}}"  name="participant-button" type="button" value="Reject" class="btn btn-sm btn-danger"  object="{{request.guest.id}}" trip="{{request.trip.id}}"/>
                </form>
            </span>
        </div>
    </div>
    <br><br>
{% endfor %}

main/templates/main/user_list.html
<div class="row well">
    <div class="col-sm-6">
        <ul class="list-group " style="height:400px;overflow-y:scroll">
    {% for profile in people_near %}
        <li class="list-group-item">
            
        
        <div class="row" >
            <div class="col-sm-4" >
                <img width="81px" height ="81px" class="media-object" src="/static/images/home/images/user-2.png" alt="">
            </div>
            <div class="col-sm-6    ">
                <h3>{{profile.user.username}}</h3>
                <h5>Joined: {{profile.user.date_joined}}</h5>
<!--                 <h5> Lives in {{profile.location.area}} </h5>
 -->                <h5>
                 <span><a href="/profile/{{profile.user.id}}/">Check {{profile.user.username}}'s Profile </a></span> <br> <br>
                </h5>
                <span> 
                    <form action="" method="POST" class="friend-request-form{{profile.user.id}}">
    					{% csrf_token %}
    					<select id="id_receiver" name="receiver" hidden>
    						<option value="{{profile.user.id}}" selected="selected" ></option>
    					</select>
    					<select id="id_sender" name="sender" hidden>
    						<option value="{{current_user.id}}" selected="selected" ></option>
    					</select>
    					<input  id="friend-request-button{{profile.user.id}}" type="button" name="friend-request-button" object="{{profile.user.id}}"  value="Send Friend Request" class="btn btn-sm btn-primary" /> <br><br> 
                    </form>
                </span><br>
            </div>
        </div>  
        </li>
        

    {% endfor %}
    </ul>
    <input  id="people_near_input" type="hidden" name="people_near_input" value="{{location_list_json}}" /> 
    <input type="hidden" name="user_location_input" object="{{user_location}}"  value="{{user_location}}" /> 
<!--     <input type="hidden" name="name_list" value="{{name_list}}"/> 
 -->    </div>
    <div class="col-sm-6">
        <meta name="viewport" content="initial-scale=1.0">
        <meta charset="utf-8">
        <style>
                html, body, #map {
                height: 400px;
                margin: 0px 0px 0px 0px;
                padding: 0px 0px 0px 5px;
                width: 100%;
                }
        </style>
        <div id="map"></div>
    </div>
</div>